version: '3.8'
services:
  web-client-error:
    image: 'app'
    build: 
      context: .
    container_name: app
    ports:
      - 8080:8080
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 4608M
        reservation:
          cpus: '0.5'
          memory: 2048M